// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62og51hFCiqyU8c3wB3CPl1LOpt67n7A',
    appId: '1:576535901550:web:d63731fcc6462962663d7f',
    messagingSenderId: '576535901550',
    projectId: 'crave-1107',
    authDomain: 'crave-1107.firebaseapp.com',
    storageBucket: 'crave-1107.firebasestorage.app',
    measurementId: 'G-7KZP57ZC3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgQvazi7jLl2OIdNIGWAEebkI89mf-kCE',
    appId: '1:576535901550:android:c1ba023af17bd8c6663d7f',
    messagingSenderId: '576535901550',
    projectId: 'crave-1107',
    storageBucket: 'crave-1107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqh4465qM0Y4aLkd33RN4inZijCO3XL_U',
    appId: '1:576535901550:ios:28c38a02c0bd62d7663d7f',
    messagingSenderId: '576535901550',
    projectId: 'crave-1107',
    storageBucket: 'crave-1107.firebasestorage.app',
    iosBundleId: 'com.example.crave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqh4465qM0Y4aLkd33RN4inZijCO3XL_U',
    appId: '1:576535901550:ios:28c38a02c0bd62d7663d7f',
    messagingSenderId: '576535901550',
    projectId: 'crave-1107',
    storageBucket: 'crave-1107.firebasestorage.app',
    iosBundleId: 'com.example.crave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62og51hFCiqyU8c3wB3CPl1LOpt67n7A',
    appId: '1:576535901550:web:33bc6d0bcafdd3d1663d7f',
    messagingSenderId: '576535901550',
    projectId: 'crave-1107',
    authDomain: 'crave-1107.firebaseapp.com',
    storageBucket: 'crave-1107.firebasestorage.app',
    measurementId: 'G-08YTKFPHTP',
  );
}
