import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../../app/app_colors.dart';
import '../../app/app_text_styles.dart';
import '../../models/meal_plan.dart';
import '../../models/recipe.dart';
import '../../services/meal_planning_service.dart';
import '../../providers/user_provider.dart';
import '../../widgets/images/smart_recipe_image.dart';
import '../../services/image_service.dart';
import 'add_meal_screen.dart';
import '../recipe_detail/recipe_detail_screen.dart';

class MealPlanningScreen extends StatefulWidget {
  const MealPlanningScreen({super.key});

  @override
  State<MealPlanningScreen> createState() => _MealPlanningScreenState();
}

class _MealPlanningScreenState extends State<MealPlanningScreen> {
  DateTime _selectedDate = DateTime.now();

  @override
  Widget build(BuildContext context) {
    return Consumer<UserProvider>(
      builder: (context, userProvider, child) {
        return ChangeNotifierProvider(
          create: (_) => MealPlanningService()..initialize(),
          child: Scaffold(
            backgroundColor: AppColors.background,
            appBar: AppBar(
              title: const Text('Meal Planning'),
              backgroundColor: AppColors.background,
              elevation: 0,
              centerTitle: true,
              titleTextStyle: AppTextStyles.titleLarge,
              actions: [
                Consumer<MealPlanningService>(
                  builder: (context, mealPlanningService, child) {
                    return Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        IconButton(
                          icon: const Icon(Icons.auto_awesome),
                          onPressed: () => _showAutoGenerateDialog(mealPlanningService),
                          tooltip: 'Auto-generate meal plan',
                        ),
                        IconButton(
                          icon: const Icon(Icons.shopping_cart),
                          onPressed: () => _showShoppingList(mealPlanningService),
                          tooltip: 'Generate shopping list',
                        ),
                      ],
                    );
                  },
                ),
              ],
            ),
            body: Consumer<MealPlanningService>(
              builder: (context, mealPlanningService, child) {
                if (mealPlanningService.isLoading) {
                  return const Center(child: CircularProgressIndicator());
                }

                return Column(
                  children: [
                    _buildWeekNavigation(mealPlanningService),
                    _buildWeekView(mealPlanningService),
                    _buildDayDetail(mealPlanningService),
                  ],
                );
              },
            ),
          ),
        );
      },
    );
  }

  Widget _buildWeekNavigation(MealPlanningService service) {
    final weekStart = service.currentWeekStart;
    final weekEnd = weekStart.add(const Duration(days: 6));
    
    return Container(
      padding: const EdgeInsets.all(16),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            onPressed: service.goToPreviousWeek,
            icon: const Icon(Icons.chevron_left),
          ),
          Column(
            children: [
              Text(
                '${DateFormat('MMM d').format(weekStart)} - ${DateFormat('MMM d, yyyy').format(weekEnd)}',
                style: AppTextStyles.titleMedium,
              ),
              if (_isCurrentWeek(weekStart))
                Text(
                  'This Week',
                  style: AppTextStyles.bodySmall.copyWith(
                    color: AppColors.primary,
                  ),
                ),
            ],
          ),
          IconButton(
            onPressed: service.goToNextWeek,
            icon: const Icon(Icons.chevron_right),
          ),
        ],
      ),
    );
  }

  Widget _buildWeekView(MealPlanningService service) {
    final weekStart = service.currentWeekStart;
    
    return Container(
      height: 100,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: 7,
        itemBuilder: (context, index) {
          final date = weekStart.add(Duration(days: index));
          final isSelected = _isSameDay(date, _selectedDate);
          final isToday = _isSameDay(date, DateTime.now());
          final mealPlan = service.getMealPlanForDate(date);
          
          return GestureDetector(
            onTap: () {
              setState(() {
                _selectedDate = date;
              });
            },
            child: Container(
              width: 80,
              margin: const EdgeInsets.only(right: 8),
              decoration: BoxDecoration(
          color: Theme.of(context).cardColor,
                borderRadius: BorderRadius.circular(16),
                border: isToday 
                    ? Border.all(color: AppColors.accent, width: 2)
                    : null,
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    DateFormat('E').format(date),
                    style: AppTextStyles.labelMedium.copyWith(
            color: Theme.of(context).colorScheme.onSurfaceVariant.withOpacity(0.5),
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    DateFormat('d').format(date),
                    style: AppTextStyles.titleMedium.copyWith(
                      color: isSelected ? AppColors.onPrimary : AppColors.textPrimary,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      _buildMealIndicator(mealPlan?.hasBreakfast ?? false, isSelected),
                      _buildMealIndicator(mealPlan?.hasLunch ?? false, isSelected),
                      _buildMealIndicator(mealPlan?.hasDinner ?? false, isSelected),
                    ],
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildMealIndicator(bool hasMeal, bool isSelected) {
    return Container(
      width: 6,
      height: 6,
      margin: const EdgeInsets.symmetric(horizontal: 1),
      decoration: BoxDecoration(
        color: hasMeal 
            ? (isSelected ? AppColors.onPrimary : AppColors.primary)
            : Colors.transparent,
        shape: BoxShape.circle,
        border: Border.all(
          color: isSelected ? AppColors.onPrimary : AppColors.textSecondary,
          width: 1,
        ),
      ),
    );
  }

  Widget _buildDayDetail(MealPlanningService service) {
    final mealPlan = service.getMealPlanForDate(_selectedDate);
    
    return Expanded(
      child: Container(
        margin: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppColors.surface,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Day header
            Padding(
              padding: const EdgeInsets.all(20),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        DateFormat('EEEE, MMMM d').format(_selectedDate),
                        style: AppTextStyles.titleLarge,
                      ),
                      if (mealPlan != null)
                        Text(
                          '${mealPlan.meals.length} meals planned',
                          style: AppTextStyles.bodyMedium.copyWith(
                            color: AppColors.textSecondary,
                          ),
                        ),
                    ],
                  ),
                  IconButton(
                    onPressed: () => _addMeal(service),
                    icon: const Icon(Icons.add_circle, color: AppColors.primary),
                  ),
                ],
              ),
            ),
            
            // Meals list
            Expanded(
              child: mealPlan == null || mealPlan.meals.isEmpty
                  ? _buildEmptyState()
                  : _buildMealsList(mealPlan, service),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.restaurant_menu,
            size: 64,
            color: AppColors.textSecondary.withOpacity(0.5),
          ),
          const SizedBox(height: 16),
          Text(
            'No meals planned',
            style: AppTextStyles.titleMedium.copyWith(
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Tap + to add your first meal',
            style: AppTextStyles.bodyMedium.copyWith(
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 24),
          ElevatedButton.icon(
            onPressed: () => _addMeal(context.read<MealPlanningService>()),
            icon: const Icon(Icons.add),
            label: const Text('Add Meal'),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.primary,
              foregroundColor: AppColors.onPrimary,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMealsList(MealPlan mealPlan, MealPlanningService service) {
    final mealsByType = <MealType, List<PlannedMeal>>{};
    
    // Group meals by type
    for (final meal in mealPlan.meals) {
      mealsByType[meal.mealType] ??= [];
      mealsByType[meal.mealType]!.add(meal);
    }

    return ListView(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      children: [
        for (final mealType in MealType.values)
          if (mealsByType[mealType]?.isNotEmpty ?? false)
            _buildMealTypeSection(mealType, mealsByType[mealType]!, service),
        
        const SizedBox(height: 20),
      ],
    );
  }

  Widget _buildMealTypeSection(MealType mealType, List<PlannedMeal> meals, MealPlanningService service) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 16),
          child: Row(
            children: [
              Text(mealType.emoji, style: const TextStyle(fontSize: 20)),
              const SizedBox(width: 8),
              Text(
                mealType.displayName,
                style: AppTextStyles.titleMedium,
              ),
              const Spacer(),
              TextButton.icon(
                onPressed: () => _addMealForType(service, mealType),
                icon: const Icon(Icons.add, size: 16),
                label: const Text('Add'),
                style: TextButton.styleFrom(
                  foregroundColor: AppColors.primary,
                ),
              ),
            ],
          ),
        ),
        
        for (final meal in meals)
          _buildMealCard(meal, service),
        
        const SizedBox(height: 16),
      ],
    );
  }

  Widget _buildMealCard(PlannedMeal meal, MealPlanningService service) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: AppColors.background,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: meal.isCooked ? Colors.green.withOpacity(0.3) : Colors.transparent,
          width: 2,
        ),
      ),
      child: ListTile(
        leading: meal.recipe != null
            ? SizedBox(
                width: 50,
                height: 50,
                child: SmartRecipeImage(
                  recipe: meal.recipe!,
                  size: ImageSize.thumbnail,
                  borderRadius: BorderRadius.circular(8),
                ),
              )
            : Container(
                width: 50,
                height: 50,
                decoration: BoxDecoration(
                  color: AppColors.primary.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  Icons.restaurant,
                  color: AppColors.primary,
                ),
              ),
        title: Text(
          meal.displayName,
          style: AppTextStyles.titleSmall.copyWith(
            decoration: meal.isCooked ? TextDecoration.lineThrough : null,
          ),
        ),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (meal.recipe != null && meal.recipe!.cookTime != null)
              Text('${meal.recipe!.cookTime} min'),
            if (meal.servings != null)
              Text('${meal.servings} serving${meal.servings! > 1 ? 's' : ''}'),
          ],
        ),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            if (!meal.isCooked)
              IconButton(
                onPressed: () => service.markMealAsCooked(_selectedDate, meal.id),
                icon: const Icon(Icons.check_circle_outline),
                color: Colors.green,
                tooltip: 'Mark as cooked',
              ),
            if (meal.isCooked)
              const Icon(Icons.check_circle, color: Colors.green),
            IconButton(
              onPressed: () => _removeMeal(service, meal),
              icon: const Icon(Icons.delete_outline),
              color: Colors.red,
              tooltip: 'Remove meal',
            ),
          ],
        ),
        onTap: meal.recipe != null
            ? () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => RecipeDetailScreen(recipe: meal.recipe!),
                  ),
                )
            : null,
      ),
    );
  }

  void _addMeal(MealPlanningService service) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddMealScreen(
          selectedDate: _selectedDate,
          mealPlanningService: service,
        ),
      ),
    );
  }

  void _addMealForType(MealPlanningService service, MealType mealType) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddMealScreen(
          selectedDate: _selectedDate,
          mealPlanningService: service,
          preselectedMealType: mealType,
        ),
      ),
    );
  }

  void _removeMeal(MealPlanningService service, PlannedMeal meal) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Remove Meal'),
        content: Text('Remove "${meal.displayName}" from your meal plan?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              service.removeMealFromPlan(_selectedDate, meal.id);
              Navigator.pop(context);
            },
            child: const Text('Remove'),
          ),
        ],
      ),
    );
  }

  void _showAutoGenerateDialog(MealPlanningService mealPlanningService) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Auto-Generate Meal Plan'),
        content: const Text(
          'Generate a weekly meal plan based on your available ingredients and recipe preferences?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              _generateWeeklyPlan(mealPlanningService);
            },
            child: const Text('Generate'),
          ),
        ],
      ),
    );
  }

  void _generateWeeklyPlan(MealPlanningService mealPlanningService) async {
    final userProvider = Provider.of<UserProvider>(context, listen: false);
    final pantryItems = userProvider.pantryList;
    
    await mealPlanningService.generateWeeklyMealPlan(
      mealPlanningService.currentWeekStart,
      pantryItems,
    );
    
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Weekly meal plan generated!')),
    );
  }

  void _showShoppingList(MealPlanningService mealPlanningService) async {
    final weekStart = mealPlanningService.currentWeekStart;
    final weekEnd = weekStart.add(const Duration(days: 6));
    
    final shoppingList = await mealPlanningService.generateShoppingList(
      weekStart,
      weekEnd,
    );
    
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Shopping List'),
        content: SizedBox(
          width: double.maxFinite,
          child: shoppingList.isEmpty
              ? const Text('No ingredients needed!')
              : ListView.builder(
                  shrinkWrap: true,
                  itemCount: shoppingList.length,
                  itemBuilder: (context, index) {
                    return ListTile(
                      leading: const Icon(Icons.shopping_cart_outlined),
                      title: Text(shoppingList[index]),
                      dense: true,
                    );
                  },
                ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
          TextButton(
            onPressed: () {
              // Add to grocery list
              final userProvider = Provider.of<UserProvider>(context, listen: false);
              for (final ingredient in shoppingList) {
                userProvider.addGroceryItem(ingredient);
              }
              Navigator.pop(context);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Added to grocery list!')),
              );
            },
            child: const Text('Add to Grocery List'),
          ),
        ],
      ),
    );
  }

  bool _isSameDay(DateTime date1, DateTime date2) {
    return date1.year == date2.year &&
           date1.month == date2.month &&
           date1.day == date2.day;
  }

  bool _isCurrentWeek(DateTime weekStart) {
    final now = DateTime.now();
    final currentWeekStart = now.subtract(Duration(days: now.weekday - 1));
    return _isSameDay(weekStart, currentWeekStart);
  }
}