import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../app/app_colors.dart';
import '../../app/app_text_styles.dart';
import '../../services/meal_planning_service.dart';
import '../../models/meal_plan.dart';
import '../../widgets/premium/premium_gate.dart';
import '../meal_planning/add_meal_screen.dart';

class WeeklyMealPlannerScreen extends StatefulWidget {
  const WeeklyMealPlannerScreen({super.key});

  @override
  State<WeeklyMealPlannerScreen> createState() => _WeeklyMealPlannerScreenState();
}

class _WeeklyMealPlannerScreenState extends State<WeeklyMealPlannerScreen> {
  DateTime _currentWeekStart = DateTime.now();

  @override
  void initState() {
    super.initState();
    _currentWeekStart = _getWeekStart(DateTime.now());
    
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Provider.of<MealPlanningService>(context, listen: false).initialize();
    });
  }

  @override
  Widget build(BuildContext context) {
    return MealPlanningGate(
      child: Scaffold(
        backgroundColor: AppColors.background,
        appBar: AppBar(
          backgroundColor: AppColors.background,
          elevation: 0,
          title: Text(
            'Meal Planner',
            style: AppTextStyles.titleLarge.copyWith(
              fontWeight: FontWeight.w600,
            ),
          ),
          actions: [
            IconButton(
              onPressed: _showPlanningOptions,
              icon: const Icon(Icons.more_vert),
            ),
          ],
        ),
        body: Consumer<MealPlanningService>(
          builder: (context, mealPlanningService, _) {
            if (mealPlanningService.isLoading) {
              return const Center(
                child: CircularProgressIndicator(),
              );
            }

            return Column(
              children: [
                _buildWeekNavigation(),
                _buildWeekOverview(mealPlanningService),
                Expanded(
                  child: _buildWeeklyGrid(mealPlanningService),
                ),
              ],
            );
          },
        ),
        floatingActionButton: FloatingActionButton.extended(
          onPressed: _showAutoGenerateDialog,
          backgroundColor: AppColors.primary,
          foregroundColor: Colors.white,
          icon: const Icon(Icons.auto_awesome),
          label: const Text('Auto Plan'),
        ),
      ),
    );
  }

  Widget _buildWeekNavigation() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.surface,
        border: Border(
          bottom: BorderSide(
            color: AppColors.primary.withOpacity(0.1),
          ),
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            onPressed: _previousWeek,
            icon: const Icon(Icons.chevron_left),
            style: IconButton.styleFrom(
              backgroundColor: AppColors.primary.withOpacity(0.1),
            ),
          ),
          Column(
            children: [
              Text(
                _formatWeekRange(_currentWeekStart),
                style: AppTextStyles.titleMedium.copyWith(
                  fontWeight: FontWeight.w600,
                ),
              ),
              Text(
                _formatMonthYear(_currentWeekStart),
                style: AppTextStyles.bodyMedium.copyWith(
                  color: AppColors.textSecondary,
                ),
              ),
            ],
          ),
          IconButton(
            onPressed: _nextWeek,
            icon: const Icon(Icons.chevron_right),
            style: IconButton.styleFrom(
              backgroundColor: AppColors.primary.withOpacity(0.1),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildWeekOverview(MealPlanningService service) {
    final stats = service.getStatistics();
    
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            AppColors.primary.withOpacity(0.1),
            AppColors.accent.withOpacity(0.05),
          ],
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          _buildStatCard(
            'Planned',
            '${stats['totalPlans']}',
            'meals',
            AppColors.primary,
          ),
          _buildStatCard(
            'Cooked',
            '${stats['cookedMeals']}',
            'meals',
            Colors.green,
          ),
          _buildStatCard(
            'Success',
            '${stats['cookingRate']}%',
            'rate',
            AppColors.accent,
          ),
        ],
      ),
    );
  }

  Widget _buildStatCard(String label, String value, String unit, Color color) {
    return Column(
      children: [
        Text(
          value,
          style: AppTextStyles.titleLarge.copyWith(
            fontWeight: FontWeight.bold,
            color: color,
          ),
        ),
        Text(
          unit,
          style: AppTextStyles.bodySmall.copyWith(
            color: color,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: AppTextStyles.bodySmall.copyWith(
            color: AppColors.textSecondary,
          ),
        ),
      ],
    );
  }

  Widget _buildWeeklyGrid(MealPlanningService service) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        children: List.generate(7, (dayIndex) {
          final date = _currentWeekStart.add(Duration(days: dayIndex));
          final mealPlan = service.getMealPlanForDate(date);
          
          return _buildDayCard(date, mealPlan, service);
        }),
      ),
    );
  }

  Widget _buildDayCard(DateTime date, MealPlan? mealPlan, MealPlanningService service) {
    final isToday = _isToday(date);
    final dayName = _getDayName(date);
    
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isToday ? AppColors.primary : AppColors.surface,
          width: isToday ? 2 : 1,
        ),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Day header
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isToday ? AppColors.primary.withOpacity(0.1) : null,
              borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      dayName,
                      style: AppTextStyles.titleMedium.copyWith(
                        fontWeight: FontWeight.w600,
                        color: isToday ? AppColors.primary : null,
                      ),
                    ),
                    Text(
                      '${date.day}/${date.month}',
                      style: AppTextStyles.bodySmall.copyWith(
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
                if (mealPlan != null && mealPlan.meals.isNotEmpty)
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: BoxDecoration(
                      color: AppColors.primary.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      '${mealPlan.meals.length} meals',
                      style: AppTextStyles.labelSmall.copyWith(
                        color: AppColors.primary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
              ],
            ),
          ),
          
          // Meal slots
          Padding(
            padding: const EdgeInsets.all(16),
            child: Column(
              children: [
                _buildMealSlot(date, MealType.breakfast, mealPlan, service),
                const SizedBox(height: 12),
                _buildMealSlot(date, MealType.lunch, mealPlan, service),
                const SizedBox(height: 12),
                _buildMealSlot(date, MealType.dinner, mealPlan, service),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMealSlot(DateTime date, MealType mealType, MealPlan? mealPlan, MealPlanningService service) {
    final meals = service.getMealsForDateTime(date, mealType);
    final hasMeal = meals.isNotEmpty;
    
    return InkWell(
      onTap: () => _addMealToSlot(date, mealType),
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: hasMeal ? _getMealTypeColor(mealType).withOpacity(0.1) : AppColors.background,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: hasMeal ? _getMealTypeColor(mealType).withOpacity(0.3) : AppColors.textSecondary.withOpacity(0.2),
            style: BorderStyle.solid,
          ),
        ),
        child: Row(
          children: [
            Icon(
              _getMealTypeIcon(mealType),
              color: hasMeal ? _getMealTypeColor(mealType) : AppColors.textSecondary,
              size: 20,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    mealType.displayName,
                    style: AppTextStyles.labelMedium.copyWith(
                      color: AppColors.textSecondary,
                    ),
                  ),
                  if (hasMeal) ...[
                    const SizedBox(height: 4),
                    ...meals.map((meal) => Text(
                      meal.displayName,
                      style: AppTextStyles.bodyMedium.copyWith(
                        fontWeight: FontWeight.w500,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    )),
                  ] else
                    Text(
                      'Tap to add meal',
                      style: AppTextStyles.bodySmall.copyWith(
                        color: AppColors.textSecondary,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                ],
              ),
            ),
            if (hasMeal)
              Icon(
                Icons.check_circle,
                color: _getMealTypeColor(mealType),
                size: 16,
              )
            else
              Icon(
                Icons.add_circle_outline,
                color: AppColors.textSecondary,
                size: 16,
              ),
          ],
        ),
      ),
    );
  }

  void _addMealToSlot(DateTime date, MealType mealType) {
    final service = Provider.of<MealPlanningService>(context, listen: false);
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => AddMealScreen(
          selectedDate: date,
          mealPlanningService: service,
          preselectedMealType: mealType,
        ),
      ),
    );
  }

  void _showAutoGenerateDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Auto-Generate Meal Plan'),
        content: const Text(
          'This will automatically plan meals for the entire week based on your pantry ingredients. Existing meals will not be overwritten.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              _generateWeeklyPlan();
            },
            child: const Text('Generate'),
          ),
        ],
      ),
    );
  }

  void _generateWeeklyPlan() async {
    final service = Provider.of<MealPlanningService>(context, listen: false);
    
    try {
      // For now, we'll pass an empty pantry list
      // In a full implementation, this would come from the user's actual pantry
      await service.generateWeeklyMealPlan(_currentWeekStart, []);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('✨ Weekly meal plan generated!'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to generate plan: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  void _showPlanningOptions() {
    showModalBottomSheet(
      context: context,
      builder: (context) => Container(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.auto_awesome),
              title: const Text('Auto-Generate Week'),
              subtitle: const Text('Let AI plan your meals'),
              onTap: () {
                Navigator.pop(context);
                _showAutoGenerateDialog();
              },
            ),
            ListTile(
              leading: const Icon(Icons.shopping_cart),
              title: const Text('Generate Shopping List'),
              subtitle: const Text('Create list from planned meals'),
              onTap: () {
                Navigator.pop(context);
                _generateShoppingList();
              },
            ),
            ListTile(
              leading: const Icon(Icons.clear_all),
              title: const Text('Clear Week'),
              subtitle: const Text('Remove all planned meals'),
              onTap: () {
                Navigator.pop(context);
                _showClearWeekDialog();
              },
            ),
          ],
        ),
      ),
    );
  }

  void _generateShoppingList() async {
    final service = Provider.of<MealPlanningService>(context, listen: false);
    final weekEnd = _currentWeekStart.add(const Duration(days: 7));
    
    try {
      final shoppingList = await service.generateShoppingList(_currentWeekStart, weekEnd);
      
      if (mounted) {
        if (shoppingList.isEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('No ingredients needed - your week is empty!'),
              backgroundColor: Colors.orange,
            ),
          );
        } else {
          _showShoppingListDialog(shoppingList);
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to generate shopping list: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  void _showShoppingListDialog(List<String> items) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Shopping List'),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView.builder(
            shrinkWrap: true,
            itemCount: items.length,
            itemBuilder: (context, index) {
              return ListTile(
                leading: const Icon(Icons.shopping_cart_outlined),
                title: Text(items[index]),
                dense: true,
              );
            },
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
          ElevatedButton(
            onPressed: () {
              // TODO: Add to grocery list
              Navigator.pop(context);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Added to grocery list!'),
                  backgroundColor: Colors.green,
                ),
              );
            },
            child: const Text('Add to Grocery List'),
          ),
        ],
      ),
    );
  }

  void _showClearWeekDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Clear Week'),
        content: const Text(
          'Are you sure you want to remove all planned meals for this week? This action cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              // TODO: Implement clear week functionality
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('Week cleared!'),
                  backgroundColor: Colors.green,
                ),
              );
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Text('Clear'),
          ),
        ],
      ),
    );
  }

  void _previousWeek() {
    setState(() {
      _currentWeekStart = _currentWeekStart.subtract(const Duration(days: 7));
    });
    Provider.of<MealPlanningService>(context, listen: false).goToPreviousWeek();
  }

  void _nextWeek() {
    setState(() {
      _currentWeekStart = _currentWeekStart.add(const Duration(days: 7));
    });
    Provider.of<MealPlanningService>(context, listen: false).goToNextWeek();
  }

  // Helper methods
  DateTime _getWeekStart(DateTime date) {
    final weekday = date.weekday;
    return DateTime(date.year, date.month, date.day).subtract(Duration(days: weekday - 1));
  }

  bool _isToday(DateTime date) {
    final now = DateTime.now();
    return date.year == now.year && date.month == now.month && date.day == now.day;
  }

  String _getDayName(DateTime date) {
    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    return days[date.weekday - 1];
  }

  String _formatWeekRange(DateTime weekStart) {
    final weekEnd = weekStart.add(const Duration(days: 6));
    return '${weekStart.day} - ${weekEnd.day}';
  }

  String _formatMonthYear(DateTime date) {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return '${months[date.month - 1]} ${date.year}';
  }

  Color _getMealTypeColor(MealType mealType) {
    switch (mealType) {
      case MealType.breakfast:
        return Colors.orange;
      case MealType.lunch:
        return Colors.green;
      case MealType.dinner:
        return Colors.blue;
      case MealType.snack:
        return Colors.purple;
    }
  }

  IconData _getMealTypeIcon(MealType mealType) {
    switch (mealType) {
      case MealType.breakfast:
        return Icons.free_breakfast;
      case MealType.lunch:
        return Icons.lunch_dining;
      case MealType.dinner:
        return Icons.dinner_dining;
      case MealType.snack:
        return Icons.cookie;
    }
  }
}